repos:
  - repo: https://github.com/dan-haus/hausify
    rev: v0.1.4
    hooks:
    -   id: hausify
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
    -   id: check-github-workflows