repos:
  - repo: local
    hooks:
      - id: hausify-py-check
        name: Hausify Python Linter/Formatter
        language: python
        entry: python3 -m hausify.main
        types: [python]
        files: ^hausify/
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
    -   id: check-github-workflows