# setup a github action that installs poetry and publishes to pypi
# trigger this action only when a tag is created

name: Publish to PyPI
on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
    branches:
      - main  # Ensure it runs only on the main branch

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml
  
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  publish:
    needs: [pre-commit, unit-tests]  # Ensure pre-commit and unit tests pass before publishing
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Ensure it runs only for version tags
    permissions:
      id-token: write  # Required for publishing to PyPI
      contents: read  # Required to read the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize repository
        uses: ./.github/actions/initialize-repo

      - name: Update version
        run: |
          poetry version ${{ github.ref_name }}  # Use the tag name as the version
          poetry build

      - name: Store the packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4

