name: Unit Testing

on: 
  - workflow_call
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize repository
        uses: ./.github/actions/initialize-repo

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov=hausify --reverse