name: Unit Testing

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH 

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv .venv
          source .venv/bin/activate
          poetry install

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov=hausify --reverse